{
  files: [
    {
      path: '/vun/css/client.45be82a7.css',
        chunk:
        Chunk {
          id: 'client',
          ids: [Array],
          debugId: 1008,
          name: 'client',
          preventIntegration: false,
          entryModule: [MultiModule],
          _modules: [SortableSet],
          filenameTemplate: undefined,
          _groups: [SortableSet],
          files: [Array],
          rendered: true,
          hash: '07d834f2706763e623c59149f848ad54',
          contentHash: [Object],
          renderedHash: '07d834f2706763e623c5',
          chunkReason: undefined,
          extraAsync: false,
          removedModules: undefined
        },
        name: 'client.css',
        isInitial: true,
        isChunk: true,
        isAsset: false,
        isModuleAsset: false
      },
      { path: '/vun/js/bundle.js',
        chunk:
        Chunk {
          id: 'client',
          ids: [Array],
          debugId: 1008,
          name: 'client',
          preventIntegration: false,
          entryModule: [MultiModule],
          _modules: [SortableSet],
          filenameTemplate: undefined,
          _groups: [SortableSet],
          files: [Array],
          rendered: true,
          hash: '07d834f2706763e623c59149f848ad54',
          contentHash: [Object],
          renderedHash: '07d834f2706763e623c5',
          chunkReason: undefined,
          extraAsync: false,
          removedModules: undefined },
        name: 'client.js',
        isInitial: true,
        isChunk: true,
        isAsset: false,
        isModuleAsset: false },
      { path: '/vun/css/client.45be82a7.css.map',
        chunk:
        Chunk {
          id: 'client',
          ids: [Array],
          debugId: 1008,
          name: 'client',
          preventIntegration: false,
          entryModule: [MultiModule],
          _modules: [SortableSet],
          filenameTemplate: undefined,
          _groups: [SortableSet],
          files: [Array],
          rendered: true,
          hash: '07d834f2706763e623c59149f848ad54',
          contentHash: [Object],
          renderedHash: '07d834f2706763e623c5',
          chunkReason: undefined,
          extraAsync: false,
          removedModules: undefined },
        name: 'client.css.map',
        isInitial: true,
        isChunk: true,
        isAsset: false,
        isModuleAsset: false },
      { path: '/vun/js/bundle.js.map',
        chunk:
        Chunk {
          id: 'client',
          ids: [Array],
          debugId: 1008,
          name: 'client',
          preventIntegration: false,
          entryModule: [MultiModule],
          _modules: [SortableSet],
          filenameTemplate: undefined,
          _groups: [SortableSet],
          files: [Array],
          rendered: true,
          hash: '07d834f2706763e623c59149f848ad54',
          contentHash: [Object],
          renderedHash: '07d834f2706763e623c5',
          chunkReason: undefined,
          extraAsync: false,
          removedModules: undefined },
        name: 'client.js.map',
        isInitial: true,
        isChunk: true,
        isAsset: false,
        isModuleAsset: false
      }
    ],
}

entrypoints = {
  client: [
    'vun/css/client.45be82a7.css',
    'vun/js/bundle.js',
    'vun/css/client.45be82a7.css.map',
    'vun/js/bundle.js.map'
  ]
}
